<template>
  <div class="db-manager">
    <div class="layout">
      <!-- Left: Table List -->
      <div class="sidebar">
        <div class="sidebar-title">数据库表</div>
        <div class="table-list">
          <div
            v-for="t in tables"
            :key="t.name"
            class="table-item"
            :class="{ active: selectedTable === t.name }"
            @click="selectTable(t.name)"
          >
            <span class="table-name">{{ t.name }}</span>
            <span class="table-count">{{ t.row_count }}</span>
          </div>
          <div v-if="tables.length === 0" class="empty-tables">暂无数据表</div>
        </div>
      </div>

      <!-- Right: Data Area -->
      <div class="main-area">
        <template v-if="selectedTable">
          <div class="toolbar">
            <span class="table-title">{{ selectedTable }}</span>
            <n-button type="primary" size="small" @click="openAddModal">
              <template #icon><n-icon><add-outline /></n-icon></template>
              新增行
            </n-button>
          </div>

          <n-data-table
            :columns="dataColumns"
            :data="rows"
            :bordered="false"
            :row-key="(row: any) => row.rowid"
            size="small"
            class="light-table"
          />

          <div class="pagination" v-if="total > pageSize">
            <n-button size="tiny" :disabled="offset === 0" @click="offset -= pageSize">上一页</n-button>
            <span class="page-info">{{ offset + 1 }}-{{ Math.min(offset + pageSize, total) }} / {{ total }}</span>
            <n-button size="tiny" :disabled="offset + pageSize >= total" @click="offset += pageSize">下一页</n-button>
          </div>
        </template>

        <div v-else class="empty-hint">
          <n-icon size="40" color="#94A3B8"><server-outline /></n-icon>
          <p>选择左侧数据表查看内容</p>
        </div>
      </div>
    </div>

    <!-- Add/Edit Modal -->
    <n-modal
      v-model:show="showModal"
      preset="card"
      :title="editingRowId ? '编辑行' : '新增行'"
      style="width: 520px; max-width: 90vw"
      :mask-closable="false"
    >
      <n-form label-placement="left" label-width="120">
        <n-form-item v-for="col in editableColumns" :key="col.name" :label="col.name">
          <n-input
            v-model:value="formFields[col.name]"
            :placeholder="col.type || 'text'"
            size="small"
          />
        </n-form-item>
      </n-form>
      <template #action>
        <div style="display: flex; justify-content: flex-end; gap: 8px">
          <n-button size="small" @click="showModal = false">取消</n-button>
          <n-button type="primary" size="small" :loading="saving" @click="doSave">保存</n-button>
        </div>
      </template>
    </n-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch, h } from "vue";
import {
  NButton, NDataTable, NModal, NForm, NFormItem, NInput, NIcon, NPopconfirm, useMessage,
} from "naive-ui";
import type { DataTableColumns } from "naive-ui";
import {
  ServerOutline,
  AddOutline,
  CreateOutline,
  TrashOutline,
} from "@vicons/ionicons5";
import {
  fetchTables,
  fetchTableSchema,
  fetchTableRows,
  insertRow,
  updateRow,
  deleteRow,
  type TableInfo,
  type ColumnInfo,
} from "../../api/db-manager";

const message = useMessage();

// ── State ───────────────────────────────────────────────────────────────────

const tables = ref<TableInfo[]>([]);
const selectedTable = ref("");
const schema = ref<ColumnInfo[]>([]);
const rows = ref<Record<string, any>[]>([]);
const total = ref(0);
const offset = ref(0);
const pageSize = 50;

// Modal
const showModal = ref(false);
const editingRowId = ref<number | null>(null);
const formFields = ref<Record<string, any>>({});
const saving = ref(false);

// ── Computed ────────────────────────────────────────────────────────────────

// Columns that users should NOT edit — auto-generated by the database
function isAutoColumn(col: ColumnInfo): boolean {
  // Primary key (e.g. id INTEGER PRIMARY KEY AUTOINCREMENT)
  if (col.pk > 0) return true;
  // rowid pseudo-column
  if (col.name === "rowid") return true;
  // Columns with CURRENT_TIMESTAMP default (created_at, updated_at, etc.)
  if (/CURRENT_TIMESTAMP/i.test(col.dflt_value || "")) return true;
  return false;
}

const editableColumns = computed(() =>
  schema.value.filter((c) => !isAutoColumn(c)),
);

/** Strip SQLite quoting from default values: 'huawei' → huawei */
function stripDefault(val: string | null): string {
  if (!val) return "";
  if (/^'.*'$/s.test(val)) return val.slice(1, -1);
  return val;
}

const dataColumns = computed<DataTableColumns>(() => {
  const cols: DataTableColumns = schema.value.map((col) => ({
    title: col.name,
    key: col.name,
    ellipsis: { tooltip: true },
    width: col.name === "rowid" ? 70 : undefined,
    render(row: any) {
      const val = row[col.name];
      if (val === null || val === undefined) return h("span", { style: "color: #94A3B8" }, "NULL");
      return h("span", { style: "font-family: 'Fira Code', monospace; color: #334155" }, String(val));
    },
  }));

  // Actions column
  cols.push({
    title: "操作",
    key: "_actions",
    width: 100,
    render(row: any) {
      return h("div", { style: "display: flex; gap: 4px" }, [
        h(
          NButton,
          { text: true, size: "tiny", quaternary: true, onClick: () => openEditModal(row) },
          { icon: () => h(NIcon, { size: 16, color: "#64748B" }, () => h(CreateOutline)) },
        ),
        h(
          NPopconfirm,
          { onPositiveClick: () => doDelete(row) },
          {
            trigger: () =>
              h(
                NButton,
                { text: true, size: "tiny", quaternary: true },
                { icon: () => h(NIcon, { size: 16, color: "#64748B" }, () => h(TrashOutline)) },
              ),
            default: () => `确定删除 rowid=${row.rowid}?`,
          },
        ),
      ]);
    },
  });

  return cols;
});

// ── Data loading ────────────────────────────────────────────────────────────

async function loadTables() {
  try {
    tables.value = await fetchTables();
  } catch {
    message.error("加载表列表失败");
  }
}

async function selectTable(name: string) {
  selectedTable.value = name;
  offset.value = 0;
  try {
    schema.value = await fetchTableSchema(name);
    await loadRows();
  } catch {
    message.error("加载表结构失败");
  }
}

async function loadRows() {
  if (!selectedTable.value) return;
  try {
    const res = await fetchTableRows(selectedTable.value, pageSize, offset.value);
    rows.value = res.rows;
    total.value = res.total;
  } catch {
    message.error("加载数据失败");
  }
}

// Reset offset -> reload
watch(offset, () => loadRows());

// ── Modal actions ───────────────────────────────────────────────────────────

function openAddModal() {
  editingRowId.value = null;
  formFields.value = {};
  for (const col of editableColumns.value) {
    formFields.value[col.name] = stripDefault(col.dflt_value);
  }
  showModal.value = true;
}

function openEditModal(row: Record<string, any>) {
  editingRowId.value = row.rowid;
  formFields.value = {};
  for (const col of editableColumns.value) {
    formFields.value[col.name] = row[col.name] ?? "";
  }
  showModal.value = true;
}

async function doSave() {
  if (!selectedTable.value) return;
  saving.value = true;
  try {
    if (editingRowId.value != null) {
      await updateRow(selectedTable.value, editingRowId.value, formFields.value);
      message.success("更新成功");
    } else {
      await insertRow(selectedTable.value, formFields.value);
      message.success("新增成功");
    }
    showModal.value = false;
    await Promise.all([loadRows(), loadTables()]);
  } catch (err: any) {
    const msg = err?.response?.data?.detail || "操作失败";
    message.error(msg);
  } finally {
    saving.value = false;
  }
}

async function doDelete(row: Record<string, any>) {
  if (!selectedTable.value) return;
  try {
    await deleteRow(selectedTable.value, row.rowid);
    message.success("删除成功");
    await Promise.all([loadRows(), loadTables()]);
  } catch (err: any) {
    const msg = err?.response?.data?.detail || "删除失败";
    message.error(msg);
  }
}

// ── Init ────────────────────────────────────────────────────────────────────

onMounted(() => loadTables());
</script>

<style scoped>
.db-manager {
  min-height: 100%;
}

.layout {
  display: flex;
  gap: 0;
  height: calc(100vh - 56px - 56px);
  margin: -28px;
}

/* ── Sidebar ─────────────────────────────────────────────────────────────── */
.sidebar {
  width: 220px;
  flex-shrink: 0;
  background: #FFFFFF;
  border-right: 1px solid #E2E8F0;
  display: flex;
  flex-direction: column;
}

.sidebar-title {
  padding: 16px 20px;
  font-size: 12px;
  font-weight: 600;
  color: #64748B;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  border-bottom: 1px solid #E2E8F0;
}

.table-list {
  flex: 1;
  overflow-y: auto;
}

.table-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 20px;
  cursor: pointer;
  transition: all 0.15s ease;
  border-bottom: 1px solid transparent;
}

.table-item:hover {
  background: #F8FAFC;
}

.table-item.active {
  background: rgba(37, 99, 235, 0.04);
  border-left: 2px solid #2563EB;
  padding-left: 18px;
}

.table-name {
  font-family: 'Fira Code', monospace;
  font-size: 13px;
  color: #334155;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.table-count {
  font-family: 'Fira Code', monospace;
  font-size: 11px;
  color: #94A3B8;
  flex-shrink: 0;
  margin-left: 8px;
}

.empty-tables {
  padding: 24px;
  text-align: center;
  color: #94A3B8;
  font-size: 13px;
}

/* ── Main Area ───────────────────────────────────────────────────────────── */
.main-area {
  flex: 1;
  padding: 20px 24px;
  overflow: auto;
  background: #F8FAFC;
}

.toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: 16px;
}

.table-title {
  font-family: 'Fira Code', monospace;
  font-size: 16px;
  font-weight: 600;
  color: #0F172A;
}

.pagination {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-top: 16px;
  justify-content: center;
}

.page-info {
  font-family: 'Fira Code', monospace;
  font-size: 12px;
  color: #64748B;
}

.empty-hint {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100%;
  gap: 12px;
  color: #94A3B8;
  font-size: 14px;
}
</style>
